# SECURITY CRITICAL: This file contains references to GCP Secret Manager
# No hardcoded secrets should ever be stored in this file
# All secrets must be managed through GCP Secret Manager and accessed via SecretManagerCSI
apiVersion: v1
kind: Secret
metadata:
  name: mas-api-secrets
  namespace: mas-system
  annotations:
    # Security audit: All secrets sourced from GCP Secret Manager
    security.policy/audit: "gcp-secret-manager-only"
    security.policy/no-hardcoded-secrets: "enforced"
type: Opaque
stringData:
  # LLM API Keys - MUST be populated from GCP Secret Manager
  # kubectl create secret generic mas-api-secrets --from-literal=GEMINI_API_KEY="$(gcloud secrets versions access latest --secret="gemini-api-key")"
  GEMINI_API_KEY: "" # To be populated from GCP Secret Manager: projects/PROJECT_ID/secrets/gemini-api-key/versions/latest
  ANTHROPIC_API_KEY: "" # To be populated from GCP Secret Manager: projects/PROJECT_ID/secrets/anthropic-api-key/versions/latest
  XAI_API_KEY: "" # To be populated from GCP Secret Manager: projects/PROJECT_ID/secrets/xai-api-key/versions/latest
  GOOGLE_CLOUD_API_KEY: "" # To be populated from GCP Secret Manager: projects/PROJECT_ID/secrets/gcp-api-key/versions/latest

  # Database URLs - MUST use Cloud SQL Auth Proxy or IAM authentication
  DATABASE_URL: "" # To be populated from GCP Secret Manager: projects/PROJECT_ID/secrets/database-url/versions/latest
  REDIS_URL: "" # To be populated from GCP Secret Manager: projects/PROJECT_ID/secrets/redis-url/versions/latest

  # Security Keys - MUST be cryptographically secure and rotated
  JWT_SECRET: "" # To be populated from GCP Secret Manager: projects/PROJECT_ID/secrets/jwt-secret/versions/latest
  ENCRYPTION_KEY: "" # To be populated from GCP Secret Manager: projects/PROJECT_ID/secrets/encryption-key/versions/latest

  # Monitoring - MUST use secure authentication
  GRAFANA_ADMIN_PASSWORD: "" # To be populated from GCP Secret Manager: projects/PROJECT_ID/secrets/grafana-admin-password/versions/latest
  
---
apiVersion: v1
kind: Secret
metadata:
  name: mas-docker-registry
  namespace: mas-system
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnY3IuaW8iOnsidXNlcm5hbWUiOiJfanNvbl9rZXkiLCJwYXNzd29yZCI6IntcbiAgXCJ0eXBlXCI6IFwic2VydmljZV9hY2NvdW50XCJcbn0iLCJhdXRoIjoiWDJwemIyNWZhMlY1T25zaUNpQWdJblI1Y0dVaU9pQWljMlZ5ZG1salpWOWhZMk52ZFc1MElncDkifX19