# TEMPORARILY DISABLED FOR QUOTA COMPLIANCE
# This deployment has been temporarily disabled to meet GCP quota requirements
# Original content below (commented out):
#
# apiVersion: v1
# data:
#   aia_rules.yml: "\ngroups:\n  - name: aia_alerts\n    rules:\n      - alert: AIAHighCPUUsage\n\
#     \        expr: (cpu_usage_percent > 80)\n        for: 5m\n        labels:\n  \
#     \        severity: warning\n        annotations:\n          summary: \"High CPU\
#     \ usage detected\"\n          description: \"CPU usage is above 80% for more than\
#     \ 5 minutes\"\n\n      - alert: AIAHighMemoryUsage\n        expr: (memory_usage_percent\
#     \ > 90)\n        for: 3m\n        labels:\n          severity: critical\n    \
#     \    annotations:\n          summary: \"High memory usage detected\"\n       \
#     \   description: \"Memory usage is above 90% for more than 3 minutes\"\n\n   \
#     \   - alert: AIAServiceDown\n        expr: up{job=\"aia-api\"} == 0\n        for:\
#     \ 1m\n        labels:\n          severity: critical\n        annotations:\n  \
#     \        summary: \"AIA API service is down\"\n          description: \"AIA API\
#     \ service has been down for more than 1 minute\"\n"
#   prometheus.yml: "\nglobal:\n  scrape_interval: 15s\n  evaluation_interval: 15s\n\
#     \nrule_files:\n  - \"aia_rules.yml\"\n\nalerting:\n  alertmanagers:\n    - static_configs:\n\
#     \        - targets:\n          - alertmanager:9093\n\nscrape_configs:\n  - job_name:\
#     \ 'aia-api'\n    static_configs:\n      - targets: ['aia-comprehensive-api:8000']\n\
#     \    metrics_path: '/metrics'\n    scrape_interval: 30s\n\n  - job_name: 'aia-frontend'\n\
#     \    static_configs:\n      - targets: ['aia-comprehensive-frontend:80']\n   \
#     \ metrics_path: '/metrics'\n    scrape_interval: 60s\n\n  - job_name: 'kubernetes-pods'\n\
#     \    kubernetes_sd_configs:\n      - role: pod\n        namespaces:\n        \
#     \  names:\n            - aia-system\n    relabel_configs:\n      - source_labels:\
#     \ [__meta_kubernetes_pod_annotation_prometheus_io_scrape]\n        action: keep\n\
#     \        regex: true\n      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]\n\
#     \        action: replace\n        target_label: __metrics_path__\n        regex:\
#     \ (.+)\n"
# kind: ConfigMap
# metadata:
#   name: prometheus-config
#   namespace: aia-monitoring
# 
