title = "gitleaks config"

[extend]
# useDefault will extend the base configuration with the default gitleaks config:
# https://github.com/zricethezav/gitleaks/blob/master/config/gitleaks.toml
useDefault = true

[[rules]]
description = "Generic API Key"
id = "generic-api-key"
regex = '''(?i)(?:key|api[[:space:]]*key|api_key|secret|token|password|pwd)[[:space:]]*[=:][[:space:]]*['\"]?([0-9a-zA-Z\-_]{10,})['\"]?'''
keywords = [
    "api_key",
    "apikey",
    "secret",
    "token",
    "password",
    "pwd"
]

[[rules]]
description = "GCP Service Account"
id = "gcp-service-account"
regex = '''(?i)(\"type\":\s*\"service_account\")'''
keywords = [
    "service_account"
]

[allowlist]
description = "global allow lists"
paths = [
    '''gitleaks.toml''',
    '''(.*?)(jpg|gif|doc|pdf|bin)$''',
    '''(go.mod|go.sum)$''',
]