# TEMPORARILY DISABLED FOR QUOTA COMPLIANCE
# This deployment has been temporarily disabled to meet GCP quota requirements
# Original content below (commented out):
#
# {
#   "steps": [
#     {
#       "name": "gcr.io/cloud-builders/docker",
#       "args": [
#         "build",
#         "-f",
#         "Dockerfile.backend-optimized",
#         "-t",
#         "gcr.io/aia-system-prod-1759055445/aia-api:$BRANCH_NAME-$SHORT_SHA",
#         "-t",
#         "gcr.io/aia-system-prod-1759055445/aia-api:latest",
#         "."
#       ]
#     },
#     {
#       "name": "gcr.io/cloud-builders/docker",
#       "args": [
#         "build",
#         "-f",
#         "Dockerfile.frontend-optimized",
#         "-t",
#         "gcr.io/aia-system-prod-1759055445/aia-frontend:$BRANCH_NAME-$SHORT_SHA",
#         "-t",
#         "gcr.io/aia-system-prod-1759055445/aia-frontend:latest",
#         "."
#       ]
#     },
#     {
#       "name": "gcr.io/cloud-builders/docker",
#       "args": [
#         "push",
#         "gcr.io/aia-system-prod-1759055445/aia-api:$BRANCH_NAME-$SHORT_SHA"
#       ]
#     },
#     {
#       "name": "gcr.io/cloud-builders/docker",
#       "args": [
#         "push",
#         "gcr.io/aia-system-prod-1759055445/aia-frontend:$BRANCH_NAME-$SHORT_SHA"
#       ]
#     },
#     {
#       "name": "gcr.io/cloud-builders/gke-deploy",
#       "args": [
#         "run",
#         "--filename=gcp-blue-green-deployment-strategy.yaml",
#         "--cluster=aia-production-optimal",
#         "--location=europe-west4",
#         "--namespace=aia-green-production"
#       ]
#     }
#   ],
#   "images": [
#     "gcr.io/aia-system-prod-1759055445/aia-api:$BRANCH_NAME-$SHORT_SHA",
#     "gcr.io/aia-system-prod-1759055445/aia-frontend:$BRANCH_NAME-$SHORT_SHA"
#   ],
#   "options": {
#     "machineType": "E2_HIGHCPU_8",
#     "diskSizeGb": "100"
#   },
#   "timeout": "1200s"
# }
