apiVersion: v1
kind: ConfigMap
metadata:
  name: stripe-payment-config
  namespace: aia-system
data:
  STRIPE_PUBLISHABLE_KEY: "pk_live_51RtkyrD7L8T9SMaOKajUOupnjUh8wS167DUFalhTcvQwuteS2JoWjSW4XDUCIOjQLwsAQplTH91ASMSlutNZfpx300KPzFlwiL"
  PAYMENT_SECURITY_MODE: "quantum_enhanced"
  PCI_DSS_LEVEL: "1"
  FRAUD_DETECTION_ENABLED: "true"
  TRANSACTION_MONITORING: "enterprise_grade"
  MAX_TRANSACTION_AMOUNT: "25000000"
  ENTERPRISE_MODE: "true"

---
apiVersion: v1
kind: Secret
metadata:
  name: stripe-payment-secrets
  namespace: aia-system
type: Opaque
data:
  # Base64 encoded secret key
  STRIPE_SECRET_KEY: c2tfbGl2ZV81MVJ0a3lyRDdMOFQ5U01hT25HbFh2Nno2WEJ0OEp4VTlZaU9iaVppOUY0QU5Yc0xOb3RLd2RiZmE5QXh3Z1lxY1k5M09uRDk2M2htTTBhc0RRRXo5d3c4MDBpa1ZjOFVtMA==
  # Base64 encoded webhook secret
  STRIPE_WEBHOOK_SECRET: d2hzZWNfcXVhbnR1bV9zZWN1cmVkX2VudGVycHJpc2Vfd2ViaG9va19lbmRwb2ludA==
  # Base64 encoded quantum encryption key
  QUANTUM_ENCRYPTION_KEY: YWlhLXF1YW50dW0tcGF5bWVudC1lbmNyeXB0aW9uLWtleS0yMDI1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stripe-payment-service
  namespace: aia-system
  labels:
    app: stripe-payment-service
    tier: payment
    security-level: quantum-enhanced
spec:
  replicas: 3
  selector:
    matchLabels:
      app: stripe-payment-service
  template:
    metadata:
      labels:
        app: stripe-payment-service
        tier: payment
        security-level: quantum-enhanced
      annotations:
        pci-dss-level: "1"
        quantum-secured: "true"
    spec:
      serviceAccountName: aia-payment-service-account
      containers:
      - name: payment-processor
        image: gcr.io/aia-system-production-2025/aia-payment-service:latest
        ports:
        - containerPort: 8000
          name: payment-api
        env:
        - name: STRIPE_PUBLISHABLE_KEY
          valueFrom:
            configMapKeyRef:
              name: stripe-payment-config
              key: STRIPE_PUBLISHABLE_KEY
        - name: STRIPE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: stripe-payment-secrets
              key: STRIPE_SECRET_KEY
        - name: STRIPE_WEBHOOK_SECRET
          valueFrom:
            secretKeyRef:
              name: stripe-payment-secrets
              key: STRIPE_WEBHOOK_SECRET
        - name: QUANTUM_ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: stripe-payment-secrets
              key: QUANTUM_ENCRYPTION_KEY
        - name: PAYMENT_SECURITY_MODE
          valueFrom:
            configMapKeyRef:
              name: stripe-payment-config
              key: PAYMENT_SECURITY_MODE
        - name: PCI_DSS_LEVEL
          valueFrom:
            configMapKeyRef:
              name: stripe-payment-config
              key: PCI_DSS_LEVEL
        - name: ENTERPRISE_MODE
          valueFrom:
            configMapKeyRef:
              name: stripe-payment-config
              key: ENTERPRISE_MODE
        - name: MAX_TRANSACTION_AMOUNT
          valueFrom:
            configMapKeyRef:
              name: stripe-payment-config
              key: MAX_TRANSACTION_AMOUNT
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        readinessProbe:
          httpGet:
            path: /api/v1/payments/config
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 10
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL

      - name: compliance-monitor
        image: gcr.io/aia-system-production-2025/aia-compliance-monitor:latest
        ports:
        - containerPort: 8001
          name: compliance-api
        env:
        - name: QUANTUM_ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: stripe-payment-secrets
              key: QUANTUM_ENCRYPTION_KEY
        - name: PCI_DSS_LEVEL
          valueFrom:
            configMapKeyRef:
              name: stripe-payment-config
              key: PCI_DSS_LEVEL
        - name: MONITORING_MODE
          value: "enterprise"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        securityContext:
          runAsNonRoot: true
          runAsUser: 1002
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true

---
apiVersion: v1
kind: Service
metadata:
  name: stripe-payment-service
  namespace: aia-system
  labels:
    app: stripe-payment-service
    tier: payment
spec:
  selector:
    app: stripe-payment-service
  ports:
  - name: payment-api
    port: 8000
    targetPort: 8000
    protocol: TCP
  - name: compliance-api
    port: 8001
    targetPort: 8001
    protocol: TCP
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: stripe-payment-loadbalancer
  namespace: aia-system
  labels:
    app: stripe-payment-service
    tier: payment-lb
  annotations:
    cloud.google.com/load-balancer-type: "External"
    service.beta.kubernetes.io/do-loadbalancer-protocol: "https"
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: "stripe-payment-ssl-cert"
spec:
  selector:
    app: stripe-payment-service
  ports:
  - name: https
    port: 443
    targetPort: 8000
    protocol: TCP
  type: NodePort

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: stripe-payment-network-policy
  namespace: aia-system
spec:
  podSelector:
    matchLabels:
      app: stripe-payment-service
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: aia-system
    - podSelector:
        matchLabels:
          tier: frontend
    ports:
    - protocol: TCP
      port: 8000
  - from: []
    ports:
    - protocol: TCP
      port: 443
  egress:
  - to: []
    ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 80
  - to:
    - podSelector:
        matchLabels:
          app: redis
    ports:
    - protocol: TCP
      port: 6379

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aia-payment-service-account
  namespace: aia-system
  annotations:
    iam.gke.io/gcp-service-account: aia-payment-service@aia-system-production-2025.iam.gserviceaccount.com

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aia-payment-service-role
rules:
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aia-payment-service-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aia-payment-service-role
subjects:
- kind: ServiceAccount
  name: aia-payment-service-account
  namespace: aia-system

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stripe-payment-ingress
  namespace: aia-system
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "aia-payment-ip"
    networking.gke.io/managed-certificates: "stripe-payment-ssl"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://013a.tech, https://aia-system.com"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, PUT, DELETE, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization"
    nginx.ingress.kubernetes.io/rate-limit: "100"
    nginx.ingress.kubernetes.io/rate-limit-window: "1m"
spec:
  tls:
  - hosts:
    - payments.013a.tech
    - payments.aia-system.com
    secretName: stripe-payment-tls
  rules:
  - host: payments.013a.tech
    http:
      paths:
      - path: /api/v1/payments
        pathType: Prefix
        backend:
          service:
            name: stripe-payment-service
            port:
              number: 8000
      - path: /api/v1/compliance
        pathType: Prefix
        backend:
          service:
            name: stripe-payment-service
            port:
              number: 8001
  - host: payments.aia-system.com
    http:
      paths:
      - path: /api/v1/payments
        pathType: Prefix
        backend:
          service:
            name: stripe-payment-service
            port:
              number: 8000
      - path: /api/v1/compliance
        pathType: Prefix
        backend:
          service:
            name: stripe-payment-service
            port:
              number: 8001

---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: stripe-payment-ssl
  namespace: aia-system
spec:
  domains:
  - payments.013a.tech
  - payments.aia-system.com

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: stripe-webhook-config
  namespace: aia-system
data:
  webhook_endpoints.json: |
    {
      "endpoints": [
        {
          "url": "https://payments.013a.tech/api/v1/payments/webhook",
          "events": [
            "payment_intent.succeeded",
            "payment_intent.payment_failed",
            "customer.subscription.created",
            "customer.subscription.updated",
            "customer.subscription.deleted",
            "invoice.payment_succeeded",
            "invoice.payment_failed"
          ],
          "description": "Primary webhook endpoint for payment processing"
        }
      ],
      "security": {
        "signature_verification": true,
        "quantum_validation": true,
        "enterprise_compliance": true
      }
    }

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: stripe-payment-monitor
  namespace: aia-system
  labels:
    app: stripe-payment-service
spec:
  selector:
    matchLabels:
      app: stripe-payment-service
  endpoints:
  - port: payment-api
    path: /metrics
    interval: 30s
  - port: compliance-api
    path: /compliance/metrics
    interval: 60s

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-alerts-config
  namespace: aia-system
data:
  alerts.yml: |
    groups:
    - name: stripe_payment_alerts
      rules:
      - alert: HighTransactionVolume
        expr: stripe_transactions_per_minute > 100
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High transaction volume detected"
          description: "Transaction rate is {{ $value }} per minute"

      - alert: PaymentFailureRate
        expr: stripe_payment_failure_rate > 0.05
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "High payment failure rate"
          description: "Payment failure rate is {{ $value }}"

      - alert: ComplianceViolation
        expr: pci_dss_compliance_score < 0.95
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "PCI DSS compliance violation"
          description: "Compliance score is {{ $value }}"

      - alert: QuantumSecurityFailure
        expr: quantum_encryption_failures > 0
        for: 0s
        labels:
          severity: critical
        annotations:
          summary: "Quantum security system failure"
          description: "Quantum encryption failures detected"

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: pci-dss-audit
  namespace: aia-system
spec:
  schedule: "0 2 * * *"  # Daily at 2 AM
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: aia-payment-service-account
          containers:
          - name: compliance-audit
            image: gcr.io/aia-system-production-2025/aia-compliance-audit:latest
            env:
            - name: QUANTUM_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe-payment-secrets
                  key: QUANTUM_ENCRYPTION_KEY
            - name: AUDIT_TYPE
              value: "full_pci_dss_audit"
            command:
            - /bin/sh
            - -c
            - "python /app/run_compliance_audit.py"
            resources:
              requests:
                memory: "128Mi"
                cpu: "100m"
              limits:
                memory: "128Mi"
                cpu: "100m"
          restartPolicy: OnFailure

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: stripe-payment-pdb
  namespace: aia-system
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: stripe-payment-service