apiVersion: v1
kind: Namespace
metadata:
  name: aia-fresh-production
  labels:
    app: aia-system
    version: "20250930"
    deployment: fresh-production
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aia-fresh-frontend
  namespace: aia-fresh-production
  labels:
    app: aia-frontend
    version: "20250930"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: aia-frontend
      version: "20250930"
  template:
    metadata:
      labels:
        app: aia-frontend
        version: "20250930"
    spec:
      containers:
      - name: frontend
        image: nginx:1.25-alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: frontend-content
          mountPath: /usr/share/nginx/html
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: frontend-content
        configMap:
          name: aia-fresh-frontend-content
      - name: nginx-config
        configMap:
          name: aia-fresh-nginx-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: aia-fresh-nginx-config
  namespace: aia-fresh-production
data:
  default.conf: |
    server {
        listen 80;
        server_name localhost;
        root /usr/share/nginx/html;
        index index.html;

        # Enable gzip compression
        gzip on;
        gzip_vary on;
        gzip_min_length 1024;
        gzip_types text/plain text/css text/xml text/javascript application/javascript application/xml+rss application/json;

        # Security headers
        add_header X-Frame-Options "SAMEORIGIN" always;
        add_header X-Content-Type-Options "nosniff" always;
        add_header X-XSS-Protection "1; mode=block" always;

        # Cache static assets
        location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
            expires 1y;
            add_header Cache-Control "public, immutable";
        }

        # API proxy for backend
        location /api/ {
            proxy_pass http://aia-fresh-backend-service/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Single Page Application routing
        location / {
            try_files $uri $uri/ /index.html;
        }

        # Health check endpoint
        location /health {
            access_log off;
            return 200 "healthy\n";
            add_header Content-Type text/plain;
        }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: aia-fresh-frontend-content
  namespace: aia-fresh-production
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>013a Analytics - Your Autonomous Analytical Partner</title>
        <meta name="description" content="Transform your data questions into comprehensive business insights with our advanced AI-powered analytical platform.">

        <!-- 013a Design System -->
        <style>
            * {
                margin: 0;
                padding: 0;
                box-sizing: border-box;
            }

            body {
                background: #1E1E1E;
                color: #F5F5DC;
                font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', system-ui, sans-serif;
                line-height: 1.6;
                min-height: 100vh;
                display: flex;
                align-items: center;
                justify-content: center;
            }

            .app-container {
                max-width: 1200px;
                padding: 2rem;
                text-align: center;
            }

            .logo {
                background: linear-gradient(135deg, #00FFFF, #FFFF00);
                -webkit-background-clip: text;
                -webkit-text-fill-color: transparent;
                background-clip: text;
                font-size: 4rem;
                font-weight: 300;
                margin-bottom: 2rem;
            }

            .tagline {
                font-size: 1.8rem;
                margin-bottom: 3rem;
                opacity: 0.9;
            }

            .description {
                font-size: 1.2rem;
                margin-bottom: 3rem;
                max-width: 800px;
                margin-left: auto;
                margin-right: auto;
                opacity: 0.8;
            }

            .cta-button {
                background: linear-gradient(135deg, #00FFFF, #FFFF00);
                color: #1E1E1E;
                padding: 1.5rem 3rem;
                border: none;
                border-radius: 50px;
                font-size: 1.3rem;
                font-weight: 600;
                cursor: pointer;
                transition: all 0.3s ease;
                text-decoration: none;
                display: inline-block;
                margin: 1rem;
            }

            .cta-button:hover {
                transform: translateY(-3px);
                box-shadow: 0 15px 35px rgba(0, 255, 255, 0.4);
            }

            .features {
                display: grid;
                grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
                gap: 2rem;
                margin-top: 4rem;
            }

            .feature-card {
                background: rgba(255, 255, 255, 0.05);
                backdrop-filter: blur(10px);
                border: 1px solid rgba(255, 255, 255, 0.1);
                border-radius: 20px;
                padding: 2rem;
                transition: all 0.3s ease;
            }

            .feature-card:hover {
                transform: translateY(-5px);
                border-color: rgba(0, 255, 255, 0.3);
            }

            .feature-icon {
                font-size: 3rem;
                margin-bottom: 1rem;
            }

            .status-indicator {
                position: fixed;
                top: 2rem;
                right: 2rem;
                background: rgba(0, 255, 0, 0.2);
                border: 2px solid #00FF00;
                border-radius: 10px;
                padding: 1rem;
                font-size: 0.9rem;
            }

            @media (max-width: 768px) {
                .logo {
                    font-size: 2.5rem;
                }
                .features {
                    grid-template-columns: 1fr;
                }
            }
        </style>
    </head>
    <body>
        <div class="status-indicator">
            🟢 System Operational
        </div>

        <div class="app-container">
            <h1 class="logo">013a Analytics</h1>
            <h2 class="tagline">Your Autonomous Analytical Partner</h2>

            <p class="description">
                Transform your data questions into comprehensive business insights with our advanced
                AI-powered analytical platform. Get Reports, Slides, and Dashboards generated
                automatically from natural language queries.
            </p>

            <div>
                <a href="/app" class="cta-button">🚀 Start Analysis</a>
                <a href="/demo" class="cta-button">🎯 View Demo</a>
            </div>

            <div class="features">
                <div class="feature-card">
                    <div class="feature-icon">🤖</div>
                    <h3>Multi-Agent AI</h3>
                    <p>Advanced AI agents work together to analyze your data from multiple perspectives and deliver comprehensive insights.</p>
                </div>

                <div class="feature-card">
                    <div class="feature-icon">🎨</div>
                    <h3>3D Visualizations</h3>
                    <p>Immersive 3D charts and interactive visualizations that make your data come alive and easy to understand.</p>
                </div>

                <div class="feature-card">
                    <div class="feature-icon">📊</div>
                    <h3>Automated Reports</h3>
                    <p>Instantly generate professional reports, presentation slides, and interactive dashboards from simple questions.</p>
                </div>

                <div class="feature-card">
                    <div class="feature-icon">🔒</div>
                    <h3>Enterprise Security</h3>
                    <p>Post-quantum cryptography and enterprise-grade security ensure your data remains protected and compliant.</p>
                </div>
            </div>

            <div style="margin-top: 4rem; opacity: 0.6;">
                <p>Powered by Advanced Intelligence Architecture (AIA)</p>
                <p>Version 2.0 - September 30, 2025</p>
            </div>
        </div>

        <script>
            // Enhanced user experience
            document.addEventListener('DOMContentLoaded', function() {
                console.log('013a Analytics - Fresh Production Deployment');
                console.log('Version: 2.0 - September 30, 2025');

                // Add smooth animations
                const cards = document.querySelectorAll('.feature-card');
                cards.forEach((card, index) => {
                    setTimeout(() => {
                        card.style.opacity = '0';
                        card.style.transform = 'translateY(20px)';
                        card.style.transition = 'all 0.6s ease';
                        card.style.opacity = '1';
                        card.style.transform = 'translateY(0)';
                    }, index * 200);
                });

                // Status indicator updates
                const statusIndicator = document.querySelector('.status-indicator');
                setInterval(() => {
                    const now = new Date().toLocaleTimeString();
                    statusIndicator.innerHTML = `🟢 System Operational<br><small>${now}</small>`;
                }, 1000);
            });
        </script>
    </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aia-fresh-backend
  namespace: aia-fresh-production
  labels:
    app: aia-backend
    version: "20250930"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aia-backend
      version: "20250930"
  template:
    metadata:
      labels:
        app: aia-backend
        version: "20250930"
    spec:
      containers:
      - name: backend
        image: us-central1-docker.pkg.dev/aia-system-production-2025/aia-docker-images/aia-api:production-latest
        ports:
        - containerPort: 8000
        env:
        - name: GOOGLE_CLOUD_PROJECT
          value: "aia-system-production-2025"
        - name: GEMINI_API_KEY
          value: "REDACTED-EMERGENCY-ROTATION"
        - name: AIA_ATOMIC_DKG_ENABLED
          value: "true"
        - name: AIA_CIRCUIT_BREAKERS_ENABLED
          value: "true"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: aia-fresh-frontend-service
  namespace: aia-fresh-production
  labels:
    app: aia-frontend
    version: "20250930"
spec:
  selector:
    app: aia-frontend
    version: "20250930"
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: aia-fresh-backend-service
  namespace: aia-fresh-production
  labels:
    app: aia-backend
    version: "20250930"
spec:
  selector:
    app: aia-backend
    version: "20250930"
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: aia-fresh-load-balancer
  namespace: aia-fresh-production
  labels:
    app: aia-system
    version: "20250930"
spec:
  selector:
    app: aia-frontend
    version: "20250930"
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 80
    protocol: TCP
    name: https
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aia-fresh-ingress
  namespace: aia-fresh-production
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "aia-global-ip"
    networking.gke.io/managed-certificates: "aia-fresh-ssl-cert"
    kubernetes.io/ingress.class: "gce"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
  - host: 013a.tech
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: aia-fresh-backend-service
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: aia-fresh-frontend-service
            port:
              number: 80
  - host: www.013a.tech
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: aia-fresh-backend-service
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: aia-fresh-frontend-service
            port:
              number: 80
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: aia-fresh-ssl-cert
  namespace: aia-fresh-production
spec:
  domains:
  - 013a.tech
  - www.013a.tech
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aia-atomic-dkg-service
  namespace: aia-fresh-production
  labels:
    app: aia-atomic-dkg
    version: "20250930"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aia-atomic-dkg
      version: "20250930"
  template:
    metadata:
      labels:
        app: aia-atomic-dkg
        version: "20250930"
    spec:
      containers:
      - name: atomic-dkg
        image: us-central1-docker.pkg.dev/aia-system-production-2025/aia-docker-images/aia-api:production-latest
        command: ["/bin/bash", "-c"]
        args:
        - |
          export PYTHONPATH=/app
          export GOOGLE_CLOUD_PROJECT=aia-system-production-2025
          export GEMINI_API_KEY=REDACTED-EMERGENCY-ROTATION
          cd /app && python -m aia.orchestration.atomic_dkg_orchestrator
        ports:
        - containerPort: 8001
        env:
        - name: GOOGLE_CLOUD_PROJECT
          value: "aia-system-production-2025"
        - name: GEMINI_API_KEY
          value: "REDACTED-EMERGENCY-ROTATION"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "100m"