# Fixed Ingress Configuration without missing security policy
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aia-production-ingress-fixed
  namespace: aia-unified-production
  annotations:
    kubernetes.io/ingress.global-static-ip-name: aia-production-ip
    ingress.gcp.kubernetes.io/managed-certificates: aia-comprehensive-ssl-certificate
    kubernetes.io/ingress.allow-http: "false"  # Force HTTPS
    cloud.google.com/armor-config: |
      {
        "default-rule": {
          "evaluate-preconfigured-expr": [
            "owasp-crs-v030001-id942110-sqli",
            "owasp-crs-v030001-id942120-sqli",
            "owasp-crs-v030001-id941100-xss"
          ]
        }
      }
    cloud.google.com/backend-config: '{"ports": {"80":"aia-backend-config-simple","8000":"aia-api-backend-config-simple"}}'
    cloud.google.com/neg: '{"ingress": true}'
spec:
  rules:
  # Main production domain
  - host: 013a.tech
    http:
      paths:
      - path: /api/*
        pathType: ImplementationSpecific
        backend:
          service:
            name: aia-unified-backend-service
            port:
              number: 8000
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: aia-unified-frontend-service
            port:
              number: 80

  # WWW redirect
  - host: www.013a.tech
    http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: aia-unified-frontend-service
            port:
              number: 80

  # Dedicated API endpoint
  - host: api.013a.tech
    http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: aia-unified-backend-service
            port:
              number: 8000

  # Founder dashboard
  - host: founder.013a.tech
    http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: aia-unified-frontend-service
            port:
              number: 80

  # Enterprise partner subdomains
  - host: ey.013a.tech
    http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: aia-unified-frontend-service
            port:
              number: 80

  - host: jpmorgan.013a.tech
    http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: aia-unified-frontend-service
            port:
              number: 80

  - host: gcp.013a.tech
    http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: aia-unified-frontend-service
            port:
              number: 80

  - host: apple.013a.tech
    http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: aia-unified-frontend-service
            port:
              number: 80
---
# Simplified Backend Configuration
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: aia-backend-config-simple
  namespace: aia-unified-production
spec:
  timeoutSec: 30
  connectionDraining:
    drainingTimeoutSec: 60
  logging:
    enable: true
    sampleRate: 0.5
  healthCheck:
    checkIntervalSec: 10
    port: 80
    type: HTTP
    requestPath: /
  cdn:
    enabled: true
    cachePolicy:
      includeHost: true
      includeProtocol: true
      includeQueryString: false

---
# API Backend Configuration
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: aia-api-backend-config-simple
  namespace: aia-unified-production
spec:
  timeoutSec: 60
  connectionDraining:
    drainingTimeoutSec: 30
  logging:
    enable: true
    sampleRate: 1.0
  healthCheck:
    checkIntervalSec: 5
    port: 8000
    type: HTTP
    requestPath: /health