apiVersion: v1
kind: Service
metadata:
  name: aia-frontend-nodeport
  namespace: aia-working-production
  labels:
    app: aia-frontend
    service: frontend
spec:
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080  # Use specific NodePort
  # No selector - using manual endpoints
---
apiVersion: v1
kind: Endpoints
metadata:
  name: aia-frontend-nodeport
  namespace: aia-working-production
subsets:
- addresses:
  - ip: 10.28.0.57  # Working frontend pod IPs
  - ip: 10.28.3.223
  - ip: 10.28.4.2
  ports:
  - name: http
    port: 80
    protocol: TCP