apiVersion: v1
kind: Service
metadata:
  name: aia-frontend-service
  namespace: aia-working-production
  labels:
    app: aia-frontend
    service: frontend
    version: v1
spec:
  selector:
    app: aia-frontend
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aia-frontend-deployment
  namespace: aia-working-production
  labels:
    app: aia-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: aia-frontend
  template:
    metadata:
      labels:
        app: aia-frontend
    spec:
      containers:
      - name: aia-frontend
        image: gcr.io/aia-system-production-2025/aia-frontend:latest
        ports:
        - containerPort: 80
          protocol: TCP
        env:
        - name: REACT_APP_API_BASE_URL
          value: "http://aia-backend-fixed-service.aia-working-production.svc.cluster.local"
        - name: REACT_APP_WEBSOCKET_URL
          value: "ws://aia-backend-fixed-service.aia-working-production.svc.cluster.local/ws"
        - name: REACT_APP_3D_ENABLED
          value: "true"
        - name: REACT_APP_DKG_ENABLED
          value: "true"
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10