# Blue-Green Deployment Strategy for AIA Microservices
# Zero-downtime deployment with automated rollback capabilities

apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: aia-backend-rollout
  namespace: aia-production
spec:
  replicas: 3
  strategy:
    blueGreen:
      activeService: aia-backend-active
      previewService: aia-backend-preview
      autoPromotionEnabled: false
      scaleDownDelaySeconds: 30
      prePromotionAnalysis:
        templates:
        - templateName: success-rate
        args:
        - name: service-name
          value: aia-backend-preview.aia-production.svc.cluster.local
      postPromotionAnalysis:
        templates:
        - templateName: success-rate
        args:
        - name: service-name
          value: aia-backend-active.aia-production.svc.cluster.local
  selector:
    matchLabels:
      app: aia-backend
  template:
    metadata:
      labels:
        app: aia-backend
    spec:
      containers:
      - name: backend
        image: us-central1-docker.pkg.dev/aia-system-prod-1759055445/aia-repo/aia-backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "postgresql://postgres:$(DATABASE_PASSWORD)@$(DATABASE_HOST):5432/aia_main"
        - name: REDIS_URL
          value: "redis://$(REDIS_HOST):6379"
        envFrom:
        - configMapRef:
            name: aia-config
        - secretRef:
            name: aia-secrets
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: aia-backend-active
  namespace: aia-production
spec:
  selector:
    app: aia-backend
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: aia-backend-preview
  namespace: aia-production
spec:
  selector:
    app: aia-backend
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP

---
# Analysis Template for Success Rate Monitoring
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
  namespace: aia-production
spec:
  args:
  - name: service-name
  metrics:
  - name: success-rate
    interval: 30s
    successCondition: result[0] >= 0.95
    failureLimit: 3
    provider:
      prometheus:
        address: http://prometheus-server.monitoring.svc.cluster.local:80
        query: |
          sum(irate(
            http_requests_total{service="{{args.service-name}}",status!~"5.."}[5m]
          )) /
          sum(irate(
            http_requests_total{service="{{args.service-name}}"}[5m]
          ))

---
# Frontend Blue-Green Rollout
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: aia-frontend-rollout
  namespace: aia-production
spec:
  replicas: 3
  strategy:
    blueGreen:
      activeService: aia-frontend-active
      previewService: aia-frontend-preview
      autoPromotionEnabled: true  # Auto-promote for frontend
      scaleDownDelaySeconds: 30
  selector:
    matchLabels:
      app: aia-frontend
  template:
    metadata:
      labels:
        app: aia-frontend
    spec:
      containers:
      - name: frontend
        image: us-central1-docker.pkg.dev/aia-system-prod-1759055445/aia-repo/aia-frontend:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: aia-frontend-active
  namespace: aia-production
spec:
  selector:
    app: aia-frontend
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: aia-frontend-preview
  namespace: aia-production
spec:
  selector:
    app: aia-frontend
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP

---
# Ingress with Blue-Green Traffic Management
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aia-blue-green-ingress
  namespace: aia-production
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "aia-global-ip"
    ingress.gcp.kubernetes.io/managed-certificates: "aia-ssl-cert"
    ingress.gcp.kubernetes.io/url-map: "aia-url-map"
spec:
  rules:
  - host: 013a.tech
    http:
      paths:
      - path: /api/*
        pathType: Prefix
        backend:
          service:
            name: aia-backend-active
            port:
              number: 8000
      - path: /*
        pathType: Prefix
        backend:
          service:
            name: aia-frontend-active
            port:
              number: 80
  - host: preview.013a.tech
    http:
      paths:
      - path: /api/*
        pathType: Prefix
        backend:
          service:
            name: aia-backend-preview
            port:
              number: 8000
      - path: /*
        pathType: Prefix
        backend:
          service:
            name: aia-frontend-preview
            port:
              number: 80

---
# Managed Certificate for SSL
apiVersion: networking.gcp.cloud.google.com/v1
kind: ManagedCertificate
metadata:
  name: aia-ssl-cert
  namespace: aia-production
spec:
  domains:
  - 013a.tech
  - www.013a.tech
  - preview.013a.tech