apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aia-live-launch-ingress
  namespace: aia-production-v2
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "aia-production-ip"
    networking.gke.io/managed-certificates: "aia-live-ssl-cert"
    kubernetes.io/ingress.class: "gce"
    networking.gke.io/v1beta1.FrontendConfig: "aia-frontend-config"
spec:
  rules:
  - host: 013a.tech
    http:
      paths:
      - path: /api/*
        pathType: ImplementationSpecific
        backend:
          service:
            name: aia-backend-api-service
            port:
              number: 8000
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: aia-frontend-service
            port:
              number: 80
  - host: www.013a.tech
    http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: aia-frontend-service
            port:
              number: 80
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: aia-live-ssl-cert
  namespace: aia-production-v2
spec:
  domains:
    - 013a.tech
    - www.013a.tech
---
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: aia-frontend-config
  namespace: aia-production-v2
spec:
  redirectToHttps:
    enabled: true
  sslPolicy: "modern-ssl-policy"