---
apiVersion: v1
kind: Service
metadata:
  name: aia-frontend-lb
  namespace: aia-production
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: aia-frontend
---
apiVersion: v1
kind: Service
metadata:
  name: aia-global-backend
  namespace: aia-production
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: aia-backend