---
# 🔐 CRYPTOGRAPHY AGENT: Quantum-Enhanced SSL Renewal System
# Mission: Comprehensive DNS/SSL/routing infrastructure renewal
# Features: Post-quantum security, circuit breakers, enterprise-grade routing
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: aia-quantum-ssl-certificate-v2
  namespace: aia-unified-production
  labels:
    app: aia-system
    component: quantum-ssl
    version: "2.0"
    renewal: "cryptography-agent-led"
  annotations:
    description: "Quantum-enhanced SSL certificate for 013a.tech production system"
    cryptography.aia.tech/renewal-policy: "automated"
    cryptography.aia.tech/quantum-ready: "true"
spec:
  domains:
  - 013a.tech
  - www.013a.tech
  - api.013a.tech
  - ey.013a.tech
  - jpmorgan.013a.tech
  - gcp.013a.tech
  - apple.013a.tech

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aia-quantum-enhanced-ingress-v2
  namespace: aia-unified-production
  labels:
    app: aia-system
    component: quantum-ingress
    version: "2.0"
    renewal: "cryptography-agent-led"
  annotations:
    # SSL Certificate Management
    ingress.gcp.kubernetes.io/managed-certificates: "aia-quantum-ssl-certificate-v2"
    kubernetes.io/ingress.global-static-ip-name: "aia-production-ip"
    kubernetes.io/ingress.allow-http: "true"

    # Quantum-Enhanced Security (Cloud Armor)
    cloud.google.com/armor-config: |
      {
        "default-rule": {
          "evaluate-preconfigured-expr": [
            "owasp-crs-v030001-id942110-sqli",
            "owasp-crs-v030001-id942120-sqli",
            "owasp-crs-v030001-id941100-xss",
            "owasp-crs-v030001-id944240-java-attack",
            "owasp-crs-v030001-id944120-rfi"
          ],
          "rate-limit-threshold": {
            "count": 100,
            "interval-sec": 60
          }
        }
      }

    # Circuit Breaker Configuration
    ingress.kubernetes.io/circuit-breaker: |
      {
        "failure-threshold": 5,
        "timeout": "30s",
        "max-requests": 3,
        "interval": "10s"
      }

    # Post-Quantum Security Headers
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Frame-Options: DENY";
      more_set_headers "X-Content-Type-Options: nosniff";
      more_set_headers "X-XSS-Protection: 1; mode=block";
      more_set_headers "Strict-Transport-Security: max-age=31536000; includeSubDomains; preload";
      more_set_headers "Content-Security-Policy: default-src 'self' https:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https:; style-src 'self' 'unsafe-inline' https:; img-src 'self' data: https:; font-src 'self' https: data:; connect-src 'self' https:; media-src 'self' https:; object-src 'none'; child-src https:; frame-ancestors 'none'; upgrade-insecure-requests;";
      more_set_headers "Referrer-Policy: strict-origin-when-cross-origin";
      more_set_headers "Permissions-Policy: camera=(), microphone=(), geolocation=(), interest-cohort=()";
      more_set_headers "Cross-Origin-Embedder-Policy: require-corp";
      more_set_headers "Cross-Origin-Opener-Policy: same-origin";
      more_set_headers "X-Quantum-Ready: enabled";
      more_set_headers "X-Cryptography-Agent: renewal-v2.0";

    # Enterprise Partner Prioritization
    nginx.ingress.kubernetes.io/server-snippet: |
      # Enterprise partner traffic prioritization
      if ($http_x_partner_id ~* "(ey|jpmorgan|gcp|apple)") {
        set $enterprise_partner "true";
      }

      # Quantum-enhanced rate limiting bypass for enterprise
      if ($enterprise_partner = "true") {
        set $rate_limit_class "enterprise";
      }

    description: "Quantum-enhanced ingress with enterprise partner support and circuit breakers"

spec:
  rules:
  # Primary Domain: 013a.tech
  - host: 013a.tech
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: aia-unified-backend-service
            port:
              number: 8000
      - path: /health
        pathType: Exact
        backend:
          service:
            name: aia-unified-backend-service
            port:
              number: 8000
      - path: /metrics
        pathType: Prefix
        backend:
          service:
            name: aia-unified-backend-service
            port:
              number: 8000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: aia-unified-frontend-service
            port:
              number: 80

  # WWW Subdomain: www.013a.tech
  - host: www.013a.tech
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: aia-unified-backend-service
            port:
              number: 8000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: aia-unified-frontend-service
            port:
              number: 80

  # API Subdomain: api.013a.tech
  - host: api.013a.tech
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: aia-unified-backend-service
            port:
              number: 8000

  # Enterprise Partner Subdomains
  - host: ey.013a.tech
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: aia-unified-frontend-service
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: aia-unified-backend-service
            port:
              number: 8000

  - host: jpmorgan.013a.tech
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: aia-unified-frontend-service
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: aia-unified-backend-service
            port:
              number: 8000

  - host: gcp.013a.tech
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: aia-unified-frontend-service
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: aia-unified-backend-service
            port:
              number: 8000

  - host: apple.013a.tech
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: aia-unified-frontend-service
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: aia-unified-backend-service
            port:
              number: 8000

---
# Circuit Breaker Service Monitor
apiVersion: v1
kind: ConfigMap
metadata:
  name: quantum-ssl-monitoring-config
  namespace: aia-unified-production
  labels:
    component: quantum-ssl-monitoring
data:
  monitoring.yaml: |
    ssl_certificate:
      name: "aia-quantum-ssl-certificate-v2"
      domains:
        - "013a.tech"
        - "www.013a.tech"
        - "api.013a.tech"
        - "ey.013a.tech"
        - "jpmorgan.013a.tech"
        - "gcp.013a.tech"
        - "apple.013a.tech"
      auto_renewal: true
      quantum_ready: true

    circuit_breakers:
      failure_threshold: 5
      timeout: "30s"
      max_requests: 3
      interval: "10s"

    enterprise_partners:
      ey: "EY Partnership - $5M pipeline"
      jpmorgan: "JPMorgan Chase - $10M pipeline"
      gcp: "Google Cloud Partnership - $7M pipeline"
      apple: "Apple Enterprise - $3M pipeline"

---
# Network Policy for Quantum Security
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: quantum-enhanced-network-policy
  namespace: aia-unified-production
  labels:
    component: quantum-security
spec:
  podSelector:
    matchLabels:
      app: aia-system
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: aia-system
    - namespaceSelector:
        matchLabels:
          name: aia-unified-production
    ports:
    - protocol: TCP
      port: 80
    - protocol: TCP
      port: 8000
    - protocol: TCP
      port: 443
  egress:
  - to: []
    ports:
    - protocol: TCP
      port: 443
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 80