apiVersion: v1
kind: ConfigMap
metadata:
  name: quantum-crypto-config
  namespace: aia-production-v2
data:
  quantum-config.json: |
    {
      "quantum_key_distribution": {
        "enabled": true,
        "key_rotation_interval": "3600s",
        "entanglement_strength": 0.99,
        "decoherence_threshold": 0.01
      },
      "post_quantum_algorithms": {
        "primary": "CRYSTALS-Kyber",
        "secondary": "CRYSTALS-Dilithium",
        "backup": "SPHINCS+",
        "key_sizes": {
          "kyber": 1024,
          "dilithium": 2048,
          "sphincs": 256
        }
      },
      "quantum_resistant_protocols": {
        "tls_version": "1.3_quantum",
        "cipher_suites": [
          "TLS_KYBER_CHACHA20_POLY1305_SHA256",
          "TLS_DILITHIUM_AES_256_GCM_SHA384",
          "TLS_SPHINCS_AES_128_GCM_SHA256"
        ]
      },
      "multi_agent_security": {
        "agent_authentication": "quantum_signature",
        "message_encryption": "post_quantum_hybrid",
        "identity_verification": "quantum_zero_knowledge",
        "consensus_algorithm": "quantum_byzantine_fault_tolerance"
      }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quantum-security-gateway
  namespace: aia-production-v2
  labels:
    app: quantum-security-gateway
    security-tier: quantum
spec:
  replicas: 3
  selector:
    matchLabels:
      app: quantum-security-gateway
  template:
    metadata:
      labels:
        app: quantum-security-gateway
        security-tier: quantum
    spec:
      containers:
      - name: quantum-crypto-processor
        image: gcr.io/PROJECT_ID/quantum-crypto:v2.0
        ports:
        - containerPort: 8443
          name: quantum-tls
        - containerPort: 9443
          name: quantum-api
        env:
        - name: QUANTUM_MODE
          value: "production"
        - name: ENTANGLEMENT_NODES
          value: "3"
        - name: DECOHERENCE_MONITORING
          value: "enabled"
        - name: POST_QUANTUM_LEVEL
          value: "256-bit"
        volumeMounts:
        - name: quantum-config
          mountPath: /etc/quantum
        - name: quantum-keys
          mountPath: /var/quantum/keys
        - name: entanglement-cache
          mountPath: /var/quantum/entanglement
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "2"
        livenessProbe:
          httpGet:
            path: /quantum/health
            port: 9443
            scheme: HTTPS
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /quantum/ready
            port: 9443
            scheme: HTTPS
          initialDelaySeconds: 30
          periodSeconds: 15
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
      volumes:
      - name: quantum-config
        configMap:
          name: quantum-crypto-config
      - name: quantum-keys
        secret:
          secretName: quantum-keys-secret
      - name: entanglement-cache
        emptyDir:
          sizeLimit: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: quantum-security-gateway-service
  namespace: aia-production-v2
  labels:
    app: quantum-security-gateway
spec:
  selector:
    app: quantum-security-gateway
  ports:
  - name: quantum-tls
    port: 8443
    targetPort: 8443
    protocol: TCP
  - name: quantum-api
    port: 9443
    targetPort: 9443
    protocol: TCP
  type: ClusterIP

---
apiVersion: v1
kind: Secret
metadata:
  name: quantum-keys-secret
  namespace: aia-production-v2
type: Opaque
data:
  # Base64 encoded quantum keys (these would be generated by quantum hardware)
  master-key: UXVhbnR1bUtleU1hc3RlcjIwMjUxMDAyCg==
  entanglement-seed: RW50YW5nbGVtZW50U2VlZFNlY3VyZVJhbmRvbQo=
  decoherence-threshold: MC4wMQo=

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: quantum-security-network-policy
  namespace: aia-production-v2
spec:
  podSelector:
    matchLabels:
      security-tier: quantum
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: aia-frontend
    - podSelector:
        matchLabels:
          app: aia-backend-api
    ports:
    - protocol: TCP
      port: 8443
    - protocol: TCP
      port: 9443
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: aia-backend-api
    ports:
    - protocol: TCP
      port: 8000
  - to: []
    ports:
    - protocol: TCP
      port: 443
    - protocol: UDP
      port: 53