# SIMPLIFIED IMMERSIVE DEPLOYMENT - FAST STARTUP
# Lightweight version for immediate testing and gradual enhancement
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-immersive-frontend
  namespace: immersive-analytics
  labels:
    app: simple-immersive-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-immersive-frontend
  template:
    metadata:
      labels:
        app: simple-immersive-frontend
    spec:
      containers:
      - name: simple-immersive-app
        image: nginx:alpine
        command: ["/bin/sh", "-c"]
        args:
        - |
          echo "🚀 Quick Immersive 3D Demo Starting..."

          # Create simple immersive landing page
          cat > /usr/share/nginx/html/index.html << 'EOF'
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>013a Analytics - Immersive Experience</title>
              <style>
                  * {
                      margin: 0;
                      padding: 0;
                      box-sizing: border-box;
                  }

                  body {
                      background: linear-gradient(135deg, #0A0A0A 0%, #1E1E1E 100%);
                      color: #F5F5DC;
                      font-family: 'Inter', -apple-system, sans-serif;
                      overflow: hidden;
                      height: 100vh;
                  }

                  .container {
                      display: flex;
                      flex-direction: column;
                      align-items: center;
                      justify-content: center;
                      height: 100vh;
                      position: relative;
                  }

                  .header {
                      position: absolute;
                      top: 20px;
                      left: 20px;
                      right: 20px;
                      display: flex;
                      justify-content: space-between;
                      align-items: center;
                      background: rgba(30, 30, 30, 0.8);
                      backdrop-filter: blur(20px);
                      border-radius: 40px;
                      padding: 12px 24px;
                      border: 1px solid rgba(0, 255, 255, 0.3);
                  }

                  .logo {
                      font-size: 20px;
                      font-weight: 600;
                      color: #F5F5DC;
                  }

                  .status {
                      display: flex;
                      gap: 12px;
                      align-items: center;
                  }

                  .chip {
                      background: rgba(0, 255, 255, 0.2);
                      color: #F5F5DC;
                      padding: 4px 12px;
                      border-radius: 20px;
                      font-size: 12px;
                      border: 1px solid rgba(0, 255, 255, 0.3);
                  }

                  .main-content {
                      text-align: center;
                      z-index: 10;
                  }

                  .title {
                      font-size: 3.5rem;
                      font-weight: 300;
                      margin-bottom: 1rem;
                      background: linear-gradient(135deg, #00FFFF 0%, #FFFF00 100%);
                      -webkit-background-clip: text;
                      -webkit-text-fill-color: transparent;
                      background-clip: text;
                  }

                  .subtitle {
                      font-size: 1.2rem;
                      margin-bottom: 2rem;
                      opacity: 0.8;
                  }

                  .features {
                      display: flex;
                      gap: 20px;
                      margin-bottom: 3rem;
                      flex-wrap: wrap;
                      justify-content: center;
                  }

                  .feature {
                      background: rgba(30, 30, 30, 0.7);
                      padding: 20px;
                      border-radius: 15px;
                      border: 1px solid rgba(255, 255, 0, 0.3);
                      min-width: 200px;
                      backdrop-filter: blur(10px);
                  }

                  .cta-button {
                      background: linear-gradient(135deg, #00FFFF 0%, #FFFF00 100%);
                      color: #1E1E1E;
                      padding: 15px 30px;
                      border: none;
                      border-radius: 25px;
                      font-size: 16px;
                      font-weight: 600;
                      cursor: pointer;
                      transition: all 0.3s ease;
                      text-decoration: none;
                      display: inline-block;
                  }

                  .cta-button:hover {
                      transform: translateY(-2px);
                      box-shadow: 0 10px 30px rgba(0, 255, 255, 0.3);
                  }

                  .particles {
                      position: absolute;
                      top: 0;
                      left: 0;
                      width: 100%;
                      height: 100%;
                      pointer-events: none;
                      z-index: 1;
                  }

                  .particle {
                      position: absolute;
                      width: 2px;
                      height: 2px;
                      background: #00FFFF;
                      border-radius: 50%;
                      opacity: 0.7;
                      animation: float 20s infinite linear;
                  }

                  @keyframes float {
                      0% {
                          transform: translateY(100vh) rotate(0deg);
                          opacity: 0;
                      }
                      10% {
                          opacity: 0.7;
                      }
                      90% {
                          opacity: 0.7;
                      }
                      100% {
                          transform: translateY(-10vh) rotate(360deg);
                          opacity: 0;
                      }
                  }

                  .info-panel {
                      position: absolute;
                      bottom: 20px;
                      right: 20px;
                      background: rgba(30, 30, 30, 0.9);
                      backdrop-filter: blur(20px);
                      border: 1px solid rgba(255, 255, 0, 0.3);
                      border-radius: 20px;
                      padding: 20px;
                      max-width: 400px;
                  }

                  .beta-badge {
                      position: absolute;
                      top: 20px;
                      right: 20px;
                      background: linear-gradient(135deg, #FF00FF 0%, #00FFFF 100%);
                      color: #1E1E1E;
                      padding: 8px 16px;
                      border-radius: 20px;
                      font-size: 12px;
                      font-weight: 600;
                  }

                  @media (max-width: 768px) {
                      .title {
                          font-size: 2.5rem;
                      }

                      .features {
                          flex-direction: column;
                          align-items: center;
                      }

                      .info-panel {
                          position: relative;
                          margin: 20px;
                          max-width: 90vw;
                      }
                  }
              </style>
          </head>
          <body>
              <div class="particles" id="particles"></div>

              <div class="header">
                  <div class="logo">013a Analytics</div>
                  <div class="status">
                      <div class="chip">2,472 atoms</div>
                      <div class="chip">WebXR Ready</div>
                      <div class="chip" id="backend-status">Connecting...</div>
                  </div>
              </div>

              <div class="beta-badge">
                  BETA
              </div>

              <div class="container">
                  <div class="main-content">
                      <h1 class="title">Immersive Analytics</h1>
                      <p class="subtitle">Experience data in three dimensions</p>

                      <div class="features">
                          <div class="feature">
                              <h3>3D Visualization</h3>
                              <p>Interactive data spheres and knowledge atoms</p>
                          </div>
                          <div class="feature">
                              <h3>Agent Marketplace</h3>
                              <p>AI-powered analytics assistants</p>
                          </div>
                          <div class="feature">
                              <h3>WebXR Support</h3>
                              <p>Full VR/AR compatibility</p>
                          </div>
                      </div>

                      <a href="https://013a.tech" class="cta-button" onclick="trackConversion()">
                          Enter Full Analytics Platform
                      </a>
                  </div>

                  <div class="info-panel">
                      <h3 style="margin-bottom: 12px;">Live Demo Available</h3>
                      <p style="font-size: 14px; line-height: 1.5; margin-bottom: 16px; opacity: 0.8;">
                          This is a preview of our immersive 3D analytics experience.
                          The full Three.js implementation is loading in parallel with WebXR support.
                      </p>
                      <p style="font-size: 12px; opacity: 0.6;">
                          Static IP: 34.117.64.236 | SSL: ✓ | CDN: Cloudflare
                      </p>
                  </div>
              </div>

              <script>
                  // Create floating particles
                  function createParticles() {
                      const container = document.getElementById('particles');
                      for (let i = 0; i < 50; i++) {
                          const particle = document.createElement('div');
                          particle.className = 'particle';
                          particle.style.left = Math.random() * 100 + '%';
                          particle.style.animationDelay = Math.random() * 20 + 's';
                          particle.style.animationDuration = (15 + Math.random() * 10) + 's';
                          container.appendChild(particle);
                      }
                  }

                  // Check backend connection
                  async function checkBackend() {
                      try {
                          const response = await fetch('/api/health');
                          const status = document.getElementById('backend-status');
                          if (response.ok) {
                              status.textContent = 'Connected';
                              status.style.background = 'rgba(0, 255, 0, 0.2)';
                              status.style.borderColor = 'rgba(0, 255, 0, 0.3)';
                          } else {
                              status.textContent = 'Demo Mode';
                              status.style.background = 'rgba(255, 165, 0, 0.2)';
                              status.style.borderColor = 'rgba(255, 165, 0, 0.3)';
                          }
                      } catch (error) {
                          const status = document.getElementById('backend-status');
                          status.textContent = 'Demo Mode';
                          status.style.background = 'rgba(255, 165, 0, 0.2)';
                          status.style.borderColor = 'rgba(255, 165, 0, 0.3)';
                      }
                  }

                  function trackConversion() {
                      console.log('User clicked CTA to full platform');
                      // Analytics tracking would go here
                  }

                  // Initialize
                  createParticles();
                  checkBackend();
                  setInterval(checkBackend, 10000);

                  // Add some keyboard shortcuts
                  document.addEventListener('keydown', function(e) {
                      if (e.key === 'f' && e.ctrlKey) {
                          e.preventDefault();
                          document.documentElement.requestFullscreen();
                      }
                      if (e.key === 'v' && e.ctrlKey) {
                          e.preventDefault();
                          alert('VR mode will be available when full WebXR loads');
                      }
                  });
              </script>
          </body>
          </html>
          EOF

          # Create health endpoint
          cat > /usr/share/nginx/html/health << 'EOF'
          healthy
          EOF

          # Configure nginx
          cat > /etc/nginx/conf.d/default.conf << 'EOF'
          server {
              listen 3000;
              server_name localhost;
              root /usr/share/nginx/html;
              index index.html;

              location / {
                  try_files $uri $uri/ /index.html;
              }

              location /health {
                  access_log off;
                  add_header Content-Type text/plain;
              }

              location /api/ {
                  proxy_pass http://aia-backend-fixed-service.aia-working-production.svc.cluster.local/;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }

              location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
                  expires 1y;
                  add_header Cache-Control "public, immutable";
                  add_header Access-Control-Allow-Origin "*";
              }
          }
          EOF

          echo "✅ Simple immersive demo ready - starting nginx"
          exec nginx -g "daemon off;"
        ports:
        - containerPort: 3000
          name: http
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
---
# Simple service
apiVersion: v1
kind: Service
metadata:
  name: simple-immersive-service
  namespace: immersive-analytics
spec:
  selector:
    app: simple-immersive-frontend
  ports:
  - port: 80
    targetPort: 3000
  type: ClusterIP