# TEMPORARILY DISABLED FOR QUOTA COMPLIANCE
# This deployment has been temporarily disabled to meet GCP quota requirements
# Original content below (commented out):
#
# apiVersion: cloud.google.com/v1
# kind: BackendConfig
# metadata:
#   name: aia-backend-config-temp
#   namespace: aia-unified-production
# spec:
#   healthCheck:
#     checkIntervalSec: 10
#     port: 8000
#     requestPath: /health
#     type: HTTP
#   timeoutSec: 30
#   connectionDraining:
#     drainingTimeoutSec: 60
#   logging:
#     enable: true
#     sampleRate: 1
#   customRequestHeaders:
#     headers:
#       - "X-Client-Region:{client_region}"
#       - "X-Client-City:{client_city}"
#       - "X-Forwarded-Proto:https"
#   cdn:
#     enabled: true
#     cachePolicy:
#       includeHost: true
#       includeProtocol: true
#       includeQueryString: false
