# Temporary LoadBalancer service for testing
apiVersion: v1
kind: Service
metadata:
  name: test-lb-service
  namespace: immersive-analytics
spec:
  type: NodePort
  selector:
    app: simple-immersive-frontend
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP